include('/Users/fabriciojacob/Documents/repositorios/catalog-service/Tiltfile')
include('/Users/fabriciojacob/Documents/repositorios/order-service-v2/Tiltfile')
include('/Users/fabriciojacob/Documents/repositorios/edge-service/Tiltfile')
include('/Users/fabriciojacob/Documents/repositorios/dispatcher-service/Tiltfile')

update_settings(max_parallel_updates=1)
