include('/home/spark/Documentos/dados/repositorios_5/catalog-service/Tiltfile')
include('/home/spark/Documentos/dados/repositorios_5/config-service/Tiltfile')
include('/home/spark/Documentos/dados/repositorios_5/order-service-v2/Tiltfile')
include('/home/spark/Documentos/dados/repositorios_6/edge-service/Tiltfile')
include('/home/spark/Documentos/dados/repositorios_6/dispatcher-service/Tiltfile')

update_settings(max_parallel_updates=1)
